countname: Migrate Blogger Entries to Independent Files
on:
  schedule:
    - cron: '34 */3 * * *'
  workflow_dispatch:

jobs:
  convert_atom_to_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Process Feed and Generate Flat Files
        uses: joshuamulder/rss-to-markdown@v1
        with:
          # Your live 2026 Atom feed link mapping
          feed_url: "https://alsunnahalislam.blogspot.com/atom.xml?redirect=false&start-index=1&max-results=9999"
          output_dir: "./_posts"
          file_extension: "md"
          template: |
            ---
            layout: post
            title: "{{title}}"
            date: {{date}}
            ---
            {{content}}
