name: Sync Blogger Posts
on:
  schedule:
    - cron: '34 */3 * * *'
  workflow_dispatch:

jobs:
  update_blog:
    name: Pull latest posts from Blogger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch RSS Feed
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://alsunnahalislam.blogspot.com/feeds/posts/default"
          readme_path: "index.html"
          max_post_count: 10
         
